/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./components/layout/AppLayout.vue')['default']
    CategoryManageSection: typeof import('./components/menu/CategoryManageSection.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElTag: typeof import('element-plus/es')['ElTag']
    LanguageSwitcher: typeof import('./components/common/LanguageSwitcher.vue')['default']
    MenuForm: typeof import('./components/MenuForm.vue')['default']
    MenuFormDialog: typeof import('./components/menu/MenuFormDialog.vue')['default']
    OrderDetailModal: typeof import('./components/OrderDetailModal.vue')['default']
    OrderHistoryModal: typeof import('./components/OrderHistoryModal.vue')['default']
    OrderHistoryPanel: typeof import('./components/dashboard/OrderHistoryPanel.vue')['default']
    OrderStatusBadge: typeof import('./components/OrderStatusBadge.vue')['default']
    OrderStatusButton: typeof import('./components/common/OrderStatusButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/layout/SideBar.vue')['default']
    SSEStatusIndicator: typeof import('./components/common/SSEStatusIndicator.vue')['default']
    TableCard: typeof import('./components/TableCard.vue')['default']
    TableSetupDialog: typeof import('./components/dashboard/TableSetupDialog.vue')['default']
    TableSetupForm: typeof import('./components/TableSetupForm.vue')['default']
    TopBar: typeof import('./components/layout/TopBar.vue')['default']
    UserForm: typeof import('./components/UserForm.vue')['default']
    UserFormDialog: typeof import('./components/user/UserFormDialog.vue')['default']
  }
}
